### ISSUE TITLE
io.py issue with conda, may want to consider renaming io.py?

### ISSUE THREAD

**Issue by ajoros** [jjrennie/GHCNpy#3]
Hi, 

Saw your talk at AMS (good job, by the way) and installed your GHCNpy package using "python setup.py install". It happened to install io.py under "/Users/<username>/GHCNpy" and this conflicts when executing any "conda" command as it returns:

```
File "/Users/ajoros/anaconda/lib/python2.7/site-packages/IPython/utils/openpy.py", line 9, in <module>
import io
File "/Users/ajoros/anaconda/bin/io.py", line 4, in <module>
__import__('pkg_resources').run_script('GHCNpy==1.0', 'io.py')
File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/__init__.py", line 25, in <module>

File "/Users/ajoros/anaconda/lib/python2.7/zipfile.py", line 501, in <module>
class ZipExtFile(io.BufferedIOBase):
AttributeError: 'module' object has no attribute 'BufferedIOBase' 
```

Googled around and it looks like "called a script in the same directory "io.py", and this is interfering with the io module in the stdlib. Rename it." 

Just a suggestion: might want to rename io.py? 

Thanks

**Comment by phobson** [comment]
I've run into this with my own libraries. I recommend renaming to iotools.py

**Comment by ajoros** [comment]
Yea I renamed it to ioghcn.py and .pyc and then it worked. In the future it
should be installed with an alternate name though so no conflict occurs.
